<?php

declare(strict_types=1);

namespace SergeR\RussianPostSDK\Enums;

enum MailCategory: string
{
    case SIMPLE = 'SIMPLE';
    case ORDERED = 'ORDERED';
    case ORDINARY = 'ORDINARY';
    case WITH_DECLARED_VALUE = 'WITH_DECLARED_VALUE';
    case WITH_DECLARED_VALUE_AND_CASH_ON_DELIVERY = 'WITH_DECLARED_VALUE_AND_CASH_ON_DELIVERY';
    case WITH_DECLARED_VALUE_AND_COMPULSORY_PAYMENT = 'WITH_DECLARED_VALUE_AND_COMPULSORY_PAYMENT';
    case WITH_COMPULSORY_PAYMENT = 'WITH_COMPULSORY_PAYMENT';
    case COMBINED = 'COMBINED';
    case COMBINED_ORDINARY = 'COMBINED_ORDINARY';
    case COMBINED_WITH_DECLARED_VALUE = 'COMBINED_WITH_DECLARED_VALUE';
    case COMBINED_WITH_DECLARED_VALUE_AND_CASH_ON_DELIVERY = 'COMBINED_WITH_DECLARED_VALUE_AND_CASH_ON_DELIVERY';
}
